### ISSUE TITLE
x=1

### ISSUE THREAD

**Issue by jciglesias** [AndreIglesias/computorV1#1]
```bash
Reduced form: 1 + Traceback (most recent call last):
  File "/tmp/computorV1/computor.py", line 304, in <module>
    poly = Polynome(eq)
  File "/tmp/computorV1/computor.py", line 38, in __init__
    self.print_info()
  File "/tmp/computorV1/computor.py", line 104, in print_info
    self.__print_reduced()
  File "/tmp/computorV1/computor.py", line 85, in __print_reduced
    if self.reduced[key].is_integer():
AttributeError: 'int' object has no attribute 'is_integer'```

**Comment by AndreIglesias** [comment]
int doesn't have method is_integer, only float
