### ISSUE TITLE
x^3 + x^2 = x + 4

### ISSUE THREAD

**Issue by jciglesias** [AndreIglesias/computorV1#3]
```bash
Reduced form: 4 + Traceback (most recent call last):
  File "/tmp/computorV1/computor.py", line 304, in <module>
    poly = Polynome(eq)
  File "/tmp/computorV1/computor.py", line 38, in __init__
    self.print_info()
  File "/tmp/computorV1/computor.py", line 104, in print_info
    self.__print_reduced()
  File "/tmp/computorV1/computor.py", line 85, in __print_reduced
    if self.reduced[key].is_integer():
AttributeError: 'int' object has no attribute 'is_integer'
```

**Comment by jciglesias** [comment]
every x needs a coefficient to avoid error

**Comment by AndreIglesias** [comment]
int don't have method is_integer
